name: Security

on:
  push:
  pull_request:

jobs:
  security:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Tools
        run: |
          pip install semgrep
          pip install pip-audit

      - name: Semgrep
        run: |
          semgrep --config auto

      - name: Custom Semgrep Rules
        run: |
          semgrep --config security/semgrep

      - name: Dependency Audit
        run: |
          pip-audit
